name: "TTA"
sample_size: 1000  # Number of MC samples for uncertainty estimation
augmentation:
  _type: Compose
  transforms:
    - _type: RandomChoice
      transforms:
        - _type: RandomAffine
          degrees: 0
          scale: [0.5, 2]
        - _type: RandomRotation
          degrees: [-45, 45]
    - _type: RandomHorizontalFlip
    - _type: RandomVerticalFlip

output:
  baseline_bath: 'results/common/'
  path: 'results/test_time_aug/'